# Question 1

In [26]:
import numpy as np
import matplotlib.pyplot as plt
import scipy as sc

def dydt(y,t):
    dydt = -2*y*t
    return dydt

#initial condition
y0 = 1
start = 0
end = 20
t = np.linspace(start,end)

#solving ode
A = sc.integrate(dydt,y0,t)
    
#plotting
plt.figure()
plt.plot(x,y)
plt.title('y(t) versus t graph')
plt.xlabel('t')
plt.ylabel('y(t)')


TypeError: 'module' object is not callable

# Question 2

In [19]:
import numpy as np
import scipy as sc

#Defining matrix A
A = np.array([[2,4,6],[5,3,2],[7,8,9]])
print(A)

[[2 4 6]
 [5 3 2]
 [7 8 9]]


In [22]:
#define matrix B
B = np.array([[18],[13],[30]])
print(B)

[[18]
 [13]
 [30]]


In [23]:
#solving vector
C = np.linalg.solve(A,B)
print (C)

[[ 4.5]
 [-7.5]
 [ 6.5]]


# Question 3

In [29]:
import requests
api_url="https://api.open-meteo.com/v1/forecast?latitude=2.375&longitude=112.5&hourly=temperature_2m&timezone=Asia%2FSingapore&forecast_days=1.json"
response = requests.get(api_url)
hourly_temperature_data=response.json()

In [40]:
def input(N,forecast):
    print("Insert number of days from 1 to 16:")
for N in range(1,6):
    days = api_url["days"]

TypeError: string indices must be integers, not 'str'